exports.up = knex => knex.schema.createTable('licitaciones_guardadas', t => {
  t.increments('id').primary()
  t.integer('empresa_id').references('id').inTable('empresas').onDelete('CASCADE')
  t.string('licitacion_id', 200).notNullable()
  t.text('titulo')
  t.string('organismo', 300)
  t.decimal('importe')
  t.date('fecha_limite')
  t.string('provincia', 100)
  t.string('municipio', 100)
  t.string('cpv', 200)
  t.text('enlace')
  t.string('estado', 30).defaultTo('nueva')
  t.text('notas')
  t.timestamps(true, true)
  t.unique(['empresa_id', 'licitacion_id'])
})

exports.down = knex => knex.schema.dropTable('licitaciones_guardadas')
